[package]
name = "gpui-todolist"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { version = "*" }
gpui-component = "0.5.0-preview2"
gpui-component-assets = "0.5.0-preview2"
anyhow = "1.0.100"
serde = "1.0.228"